#!/usr/bin/env node
/**
 * Writes .env for docker-compose.yml from this machine: time zone, host name
 * and where Claude Code and Codex keep their session files (used for token
 * usage). Works on Windows, macOS and Linux. Run it once before
 * `docker compose up -d --build`, and again if any of those change.
 *
 *   node setup.js
 */

'use strict';

const fs = require('fs');
const os = require('os');
const path = require('path');

const home = os.homedir();
const fwd = p => p.replace(/\\/g, '/');

// Agents' session folders. A folder that does not exist (agent not installed)
// is mounted from an empty placeholder instead, so nothing is created in $HOME.
const placeholder = path.join(__dirname, 'data', '.empty');
const sources = [
  ['CLAUDE', path.join(home, '.claude', 'projects'), '/host/claude-projects'],
  ['CODEX', path.join(home, '.codex', 'sessions'), '/host/codex-sessions'],
];

const lines = [
  '# Generated by `node setup.js` on ' + new Date().toISOString().slice(0, 10) + '. Re-run it instead of editing by hand.',
  'AM_TZ=' + (Intl.DateTimeFormat().resolvedOptions().timeZone || 'UTC'),
  'AM_HOST_LABEL=' + os.hostname(),
];
const map = [];
for (const [name, dir, mount] of sources) {
  const found = fs.existsSync(dir);
  if (!found) fs.mkdirSync(placeholder, { recursive: true });
  lines.push(`AM_${name}_DIR=${fwd(found ? dir : placeholder)}`);
  map.push(`${dir}=${mount}`);
  console.log(`${name.padEnd(7)} ${found ? dir : '(not found, skipped: ' + dir + ')'}`);
}
lines.push('AM_PATH_MAP=' + map.join(';'));

fs.writeFileSync(path.join(__dirname, '.env'), lines.join('\n') + '\n');
console.log('\nWrote .env  (time zone ' + lines[1].split('=')[1] + '). Next: docker compose up -d --build');
